### ISSUE TITLE
needed to copy netcdf_translate.sh to dir after file_sort

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-netcdf#1]
the instructions did not mention that netcdf_translate.sh is needed in directory or error 'file not found'

**Comment by ghost** [comment]
netcdf_translate.sh was not designed to be called directly, but is to be called by batch_translate.sh. As such, instructions were not included for its use.

Using and modifying batch_translate.sh to fit your purpose should alleviate this issue.

**Comment by ivanhanigan** [comment]
@calvin-curtin It was not called by me. It was called by batch_translate but could not be found so I had to go and figure out why.  It would be kinder to the user to instruct the proper way that it should be configured and minimise unclear warnings about "file not found"  thanks

**Comment by MilesSowden** [comment]
Script leaves the code folder and loses the netcdf_translate.sh file.
Solution grab code folder before cd

**Comment by MilesSowden** [comment]
Issue should be closed. The script should end with cd - to return to the calling subdirectory.
