### ISSUE TITLE
v1.3: coastal pixels

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-netcdf#12]
We can think of two options.

1. `terra::focal_statistics` with extrapolate (max would mean all the 1's or 0's
2. get polygons around coast and take intersect

**Comment by ivanhanigan** [comment]
@cassandrayuen wrote: "Hi Ivan,
```
I think the SA1 extrapolation method won’t work out too well. See Sydney region below (Red overlay is V1.2 grid, green polygons are SA1 polygons). Quite a lot of SA1s that are well-populated don’t overlap with the grid.

I will default to our second method, a focal max of sorts – considering the few pixels that are missing, will buffer on the missing pixels, take the max flag of pixels within the buffer. Let me know if you object or have other ideas.
```

I agree that the focal_statistics method is a good approach

**Comment by cassandrayuen** [comment]
Final process was to buffer each missing pixel of V1.3 with a 15km radius buffer and check the V1.2 flags within that buffer. If **any** of the V1.2 pixels are flagged, then flag the V1.3 pixel.

This buffer radius was sufficient to add flags to most V1.3 pixels - only a few V1.3 pixels are missing flags and are all remote/small islands.
