### ISSUE TITLE
CRS should be "EPSG:3577"

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-netcdf#3]
GDA94 / Australian Albers

The nc file has a bunch of info but not this code.

QGIS cannot identify from the file (loads as Unknown CRS)

**Comment by fredfarivar** [comment]
created a pull req to fix this problem. 
![Capture](https://user-images.githubusercontent.com/82791736/168978543-dfff12b3-cc7b-44fe-a150-0940729c03db.JPG)

**Comment by MilesSowden** [comment]
Ideally this should be more generic with this information being passed by the user (or in a initialization file)

**Comment by fredfarivar** [comment]
That's a good idea Miles!

**Comment by ivanhanigan** [comment]
@MilesSowden and @foadfarivar the XML is a good idea for this as Miles already pointed out in _Originally posted by @MilesSowden in https://github.com/cardat/air-health-bushfire-smoke-netcdf/issues/4#issuecomment-1129734091_

we can use the tool that I already use to generate XML using the Ecological Metadata Language (EML) schema  https://github.com/ropensci/EML and https://sbclter.msi.ucsb.edu/external/InformationManagement/EML_211_schema/docs/eml-2.1.1/index.html

I will have a go at generating an example XML now

**Comment by ivanhanigan** [comment]
Closing with reference to XML suggested by @MilesSowden https://github.com/cardat/air-health-bushfire-smoke-netcdf/issues/4#issuecomment-1129734091
