### ISSUE TITLE
meet minimum CF compliance 

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-netcdf#5]
merge_clean.sh says "update the file metadata to ensure CF compliance."
what is needed?  Is the long_name for each Band?  the description "active_fires: 10000 m resolution" is wrong, it is the boolean flag whether there were active fires in a 10000m buffer of each pixel.  do all bands need long_names?

**Comment by ghost** [comment]
CF documentation suggest that we will require a long name for each band and some additional global metadata.

If the description is incorrect, please provide a schema specifying the accurate long names of each band. 

Additional global metadata could include:
- Source: Description of how the data was generated
- References: Authors
- Comments: Any miscellaneous comments, perhaps usage or license information.

At the time of writing the scripts, the majority of the above information was unknown and therefore placeholders were used. We can hardcode the metadata in, or we could provide further instructions for a user to input the information as required. (i.e. User may only wish to merge specific layers and will need to add the long names as required)

@MilesSowden Please advise if there are further requirements to ensure CF compliance.

**Comment by ghost** [comment]
Handled in #4

**Comment by MilesSowden** [comment]
Yep happy this is closed. @ivanhanigan you agree?
